In [1]:
from scripts.manager import Manager
from scripts.manager import rank_models
from scripts.plots import compare_hmm_rnn_euclidean_distances, compare_hmm_rnn_transition_matrices

## Run Grid Search

Now we'll run the grid search with selected configurations, hidden sizes, and input sizes.

In [ ]:
manager = Manager()
results = manager.run_grid_search(
    configs=["HMMFive"],
    hidden_sizes=[200],
    input_sizes=[100],
    seeds=[32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48 , 49, 50],
    verbose=False,
)

In [2]:
import json

with open('/home/elia/Documents/rnnrep/Experiments/grid_search_20250412_021154/grid_search_results.json', 'r') as f:
    data = json.load(f)

experiments = data['experiments']
ranking = rank_models(experiments)
configs = ["HMMTwo", "HMMThree", "HMMFour", "HMMFive"]
for config in configs:
    print()
    print(config)
    for i in range(len(ranking[config])):
        print(ranking[config][i])



HMMTwo
{'hidden_size': 200, 'input_size': 100, 'average_loss': 9.738074514600966, 'std_loss': 0.09424116169477967}
{'hidden_size': 200, 'input_size': 200, 'average_loss': 9.752340210808647, 'std_loss': 0.08699436703188582}
{'hidden_size': 200, 'input_size': 10, 'average_loss': 9.764152526855469, 'std_loss': 0.09511420074227955}
{'hidden_size': 150, 'input_size': 10, 'average_loss': 9.789328469170465, 'std_loss': 0.060425050888595816}
{'hidden_size': 200, 'input_size': 1, 'average_loss': 9.818995157877604, 'std_loss': 0.17358676909322454}
{'hidden_size': 150, 'input_size': 1, 'average_loss': 9.841972986857096, 'std_loss': 0.1086589167678319}
{'hidden_size': 150, 'input_size': 100, 'average_loss': 9.85722827911377, 'std_loss': 0.07042415595660552}
{'hidden_size': 150, 'input_size': 200, 'average_loss': 9.895016882154676, 'std_loss': 0.13022933561017835}
{'hidden_size': 50, 'input_size': 100, 'average_loss': 9.951488282945421, 'std_loss': 0.05715348499203837}
{'hidden_size': 50, 'input_s

## Run Metrics

In [2]:
compare_hmm_rnn_euclidean_distances()
compare_hmm_rnn_transition_matrices()

Processing HMMTwo models...
  Processing hidden_50...
    Processing input_1...
      Processing seed_0...
        Processing model: 2HMM_3Outputs_linear_30kData_0.001lr_10.0Loss.pth
Transition Matrix:
[[0.95 0.05]
 [0.05 0.95]]
Emission Probabilities:
[[0.99 0.01 0.  ]
 [0.   0.01 0.99]]
        Using num_seq=5000, seq_len=100
        Generating HMM test sequences...
        Generating RNN test sequences...
        Matching sequences...


/home/elia/Documents/rnnrep/scripts/plots.py:665: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  hmm_data2_flat = torch.tensor(hmm_data2_flat).float().to(device)
/home/elia/Documents/rnnrep/scripts/plots.py:668: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  hmm_data3_flat = torch.tensor(hmm_data3_flat).float().to(device)
/home/elia/Documents/rnnrep/scripts/plots.py:679: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  hmm_data_flat = torch.tensor(hmm_data_flat).float().to(device)


        Calculating Euclidean distances...
      Processing seed_1...
        Processing model: 2HMM_3Outputs_linear_30kData_0.001lr_10.0Loss.pth
Transition Matrix:
[[0.95 0.05]
 [0.05 0.95]]
Emission Probabilities:
[[0.99 0.01 0.  ]
 [0.   0.01 0.99]]
        Using num_seq=5000, seq_len=100
        Generating HMM test sequences...
        Generating RNN test sequences...
        Matching sequences...
        Calculating Euclidean distances...
      Processing seed_2...
        Processing model: 2HMM_3Outputs_linear_30kData_0.001lr_9.9Loss.pth
Transition Matrix:
[[0.95 0.05]
 [0.05 0.95]]
Emission Probabilities:
[[0.99 0.01 0.  ]
 [0.   0.01 0.99]]
        Using num_seq=5000, seq_len=100
        Generating HMM test sequences...
        Generating RNN test sequences...
        Matching sequences...
        Calculating Euclidean distances...
    Processing input_10...
      Processing seed_0...
        Processing model: 2HMM_3Outputs_linear_30kData_0.001lr_10.1Loss.pth
Transition Matrix:

defaultdict(<function scripts.plots.compare_hmm_rnn_transition_matrices.<locals>.<lambda>()>,
            {'HMMTwo': defaultdict(<function scripts.plots.compare_hmm_rnn_transition_matrices.<locals>.<lambda>.<locals>.<lambda>()>,
                         {'hidden_50': defaultdict(list,
                                      {'input_1': (array([[1.31842214e-03, 2.98090434e-05, 1.66470492e-03],
                                               [1.53923688e-03, 9.79263693e-03, 4.94866129e-03],
                                               [1.23976775e-03, 3.51188598e-05, 9.15799570e-04]]),
                                        array([[1.38166283e-03, 6.81108233e-06, 1.51514244e-03],
                                               [1.09988287e-03, 1.45926438e-03, 4.01573160e-03],
                                               [9.28236801e-04, 1.15230634e-05, 8.55849305e-04]])),
                                       'input_10': (array([[1.05227084e-04, 7.62443997e-05, 3.48729138e-04],
       